server:
  port: 8800
  servlet:
    encoding:
      enabled: true
      charset: GBK
      force: true
  tomcat:
    uri-encoding: GBK
druid:
  allow:
    ip: 127.0.0.1
  login:
    user_name: root
    password: 12345678
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.90.248.61:1521:edbyms1
    username: edbadm
    password: adm1234
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池的配置信息
    # 初始化⼤⼩，最⼩等待连接数量，最⼤等待连接数量，最⼤连接数
    initialSize: 1
    minIdle: 1
    maxIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进⾏⼀次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置⼀个连接在池中最⼩⽣存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的⼤⼩
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界⾯sql⽆法统计，'wall'⽤于防⽕墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties:
      druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true